version: "3.7"

services:
  nurd:
    build: .
    ports: 
      - 8080:8080
    environment:
      CONNECTION_STRING: Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword;
  mssql:
    image: microsoft/mssql-server-linux
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: yourStrong(!)Password
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000


